### ISSUE TITLE
Let's bring back the site

### ISSUE THREAD

**Issue by jeffmicklos** [GavinJoyce/ember-beats#18]
Saw your great topic about Radiohead beats on Reddit and it got me super stoked to play with your toy! What will it take to get the site up and running again? A code or server problem? Either way, I will build locally and play!

**Comment by GavinJoyce** [comment]
Oh, thanks for the pointer. I'll fix the website over the weekend. Let me know if you can't get it running locally

**Comment by GavinJoyce** [comment]
Sorry for the long delay, the website is back: http://emberbeats.gavinjoyce.com/
